general:

  steps: (
  gctsDeploy:
    host: 'https://hclutl1909.hcldigilabs.com:8001'
    client: '000'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'OpenSAP'
    remoteRepositoryURL: "https://remote.repository.url.com"
    role: 'Provided'
    vSID: 'FEF'
    branch: 'master'
    rollback: false
    )
    
   steps: (
  gctsExecuteABAPUnitTests:
    host: 'https://hclutl1909.hcldigilabs.com:8001'
    client: '200'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'OpenSAP' 
    )
    
    steps:
  (
  gctsRollback:
    host: 'https://hcluks4hana.hcldigilabs.com:8001'
    client: '200'
    abapCredentialsId: 'AbapSystem'
    repository: 'OpenSAP'
   
    )
