
steps:
  gctsExecuteABAPUnitTests:
   host: 'https://hcluks4hana.hcldigilabs.com:8001',
client: '200',	
abapCredentialsId: 'AbapSystem',
repository: 'HCL-DevOps-V1'



steps:
  gctsRollback:
    host: "https://hcluks4hana.hcldigilabs.com:8001/",
    client: "200",
    abapCredentialsId: 'AbapSystem',
    repository: "HCL-DevOps-V1"
    
    steps:
  gctsCreateRepository:
    host: 'https://hclutl1909.hcldigilabs.com:8001',
    client: '200',
    abapCredentialsId: 'ABAPUserPasswordCredentialsId',
    repository: 'HCL-DevOps-V2',
    remoteRepositoryURL: 'https://github.com/abhilashhaa/OpenSAPDemo.git',
    role: 'TARGET',
    vSID: 'FEF'
    
    steps:
  gctsCloneRepository:
    host: 'https://hclutl1909.hcldigilabs.com:8001',
    client: '200',
    abapCredentialsId: 'ABAPUserPasswordCredentialsId',
    repository: 'HCL-DevOps-V2'
    
    steps:
  gctsDeploy:
    host: 'https://hclutl1909.hcldigilabs.com:8001',
  abapCredentialsId: 'ABAPUserPasswordCredentialsId',
  repository: 'HCL-DevOps-V2',
  remoteRepositoryURL: "https://github.com/abhilashhaa/OpenSAPDemo.git",
  role: 'TARGET',
  vSID: 'FEF',
  rollback: 'false',
    
