general:

stages:
<...>
  gctsDeploy:
    host: 'https://hclutl1909.hcldigilabs.com:8001'
    client: '200'
    abapCredentialsId: 'AbapSystem'
    repository: 'OpenSAP' 
    
    steps:
  <...>
  gctsExecuteABAPUnitTests:
    host: 'https://hclutl1909.hcldigilabs.com:8001'
    client: '200'
    abapCredentialsId: 'AbapSystem'
    repository: 'OpenSAP' 
    
    steps:
  <...>
  gctsRollback:
    host: 'https://hclutl1909.hcldigilabs.com:8001'
    client: '200'
    abapCredentialsId: 'AbapSystem'
    repository: 'OpenSAP' 
