PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !I_KNUMV MODULE %_I_KNUMV .

FIELD !I_KPOSN MODULE %_I_KPOSN .

FIELD !I_STUNR MODULE %_I_STUNR .

FIELD !I_ZAEHK MODULE %_I_ZAEHK .

CHAIN.
  FIELD I_KNUMV .
  FIELD I_KPOSN .
  FIELD I_STUNR .
  FIELD I_ZAEHK .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.